### PR TITLE
Updated Texas NAIP Imagery to 2012 to 2014.

### PR DESCRIPTION
**Pull request by kristenkam**
Removed the 2012 XML file. Tested and it works!

### CODE REVIEW

**Comment by rjhale1971** [comment]
Thank you!

**Comment by kristenkam** [comment]
You're welcome. I'll continue to work on the others. =)

**Comment by rjhale1971** [comment]
Good Deal - this has been on my list to clean up. Haven't had the time. I think the URL changed in some and there have been new fly overs in others. You Rock.

**Comment by kristenkam** [comment]
I use the NAIP imagery quite a bit. I'll go over the list today and update. I think my next step is to maybe come up with some kind of plugin that loads the data to QGIS and refreshes the WMS connections whenever there is a change to the GIT repository. Sound good?

**Comment by rjhale1971** [comment]
Works for me. That would be pretty awe inspiring.

**Pull request merged**
